# Generated by Django 4.0.6 on 2022-07-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScraperProcess',
        ),
    ]
