# Generated by Django 4.0.6 on 2022-07-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='cell_mode',
        ),
        migrations.RemoveField(
            model_name='device',
            name='cell_op',
        ),
        migrations.RemoveField(
            model_name='device',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='device',
            name='nick',
        ),
        migrations.AddField(
            model_name='device',
            name='airplane_fix_command',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_reset_command',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name_of_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(choices=[('motorola', 'MOTOROLA'), ('samsung', 'SAMSUNG')], default='', max_length=255),
        ),
    ]
