# Generated by Django 4.0.6 on 2022-07-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_remove_device_cell_mode_remove_device_cell_op_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='airplane_fix_command',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ip_reset_command',
        ),
    ]
